import { UserConfigFn } from "vite";
import { overrideVaadinConfig } from "./vite.generated";

const customConfig: UserConfigFn = (env) => ({
  plugins: [
    {
      name: "my-custom-plugin",
      enforce: "post",
      config(config) {
        config.plugins = config.plugins?.filter((plugin) => {
          // @ts-ignore
          return plugin?.name !== "vaadin:bundles";
        });
        config.optimizeDeps!.force = true;
        config.optimizeDeps!.include = [
          "@vaadin/accordion",
          "@vaadin/app-layout",
          "@vaadin/app-layout/vaadin-drawer-toggle.js",
          "@vaadin/avatar",
          "@vaadin/avatar-group",
          "@vaadin/button",
          "@vaadin/card",
          "@vaadin/checkbox",
          "@vaadin/checkbox-group",
          "@vaadin/combo-box",
          "@vaadin/combo-box/lit.js",
          "@vaadin/context-menu",
          "@vaadin/context-menu/lit.js",
          "@vaadin/custom-field",
          "@vaadin/date-picker",
          "@vaadin/date-time-picker",
          "@vaadin/details",
          "@vaadin/dialog",
          "@vaadin/dialog/lit.js",
          "@vaadin/email-field",
          "@vaadin/field-highlighter",
          "@vaadin/form-layout",
          "@vaadin/form-layout/vaadin-form-row.js",
          "@vaadin/form-layout/vaadin-form-item.js",
          "@vaadin/grid",
          "@vaadin/grid/lit.js",
          "@vaadin/grid/vaadin-grid-column-group.js",
          "@vaadin/grid/vaadin-grid-column.js",
          "@vaadin/grid/vaadin-grid-filter.js",
          "@vaadin/grid/vaadin-grid-selection-column.js",
          "@vaadin/grid/vaadin-grid-sorter.js",
          "@vaadin/grid/vaadin-grid-tree-toggle.js",
          "@vaadin/horizontal-layout",
          "@vaadin/icon",
          "@vaadin/icons",
          "@vaadin/integer-field",
          "@vaadin/item",
          "@vaadin/list-box",
          "@vaadin/lit-renderer",
          "@vaadin/login",
          "@vaadin/login/vaadin-login-overlay.js",
          "@vaadin/login/vaadin-login-form.js",
          "@vaadin/markdown",
          "@vaadin/master-detail-layout",
          "@vaadin/menu-bar",
          "@vaadin/message-input",
          "@vaadin/message-list",
          "@vaadin/multi-select-combo-box",
          "@vaadin/multi-select-combo-box/lit.js",
          "@vaadin/notification",
          "@vaadin/notification/lit.js",
          "@vaadin/number-field",
          "@vaadin/overlay",
          "@vaadin/password-field",
          "@vaadin/popover",
          "@vaadin/progress-bar",
          "@vaadin/radio-group",
          "@vaadin/scroller",
          "@vaadin/select",
          "@vaadin/select/lit.js",
          "@vaadin/side-nav",
          "@vaadin/side-nav/vaadin-side-nav-item.js",
          "@vaadin/split-layout",
          "@vaadin/tabs",
          "@vaadin/tabsheet",
          "@vaadin/text-area",
          "@vaadin/text-field",
          "@vaadin/time-picker",
          "@vaadin/tooltip",
          "@vaadin/upload",
          "@vaadin/vertical-layout",
          "@vaadin/virtual-list",
          "@vaadin/virtual-list/lit.js",
          "@vaadin/board",
          "@vaadin/charts",
          "@vaadin/confirm-dialog",
          "@vaadin/crud",
          "@vaadin/dashboard",
          "@vaadin/grid-pro",
          "@vaadin/grid-pro/lit.js",
          "@vaadin/grid-pro/vaadin-grid-pro-edit-column.js",
          "@vaadin/map",
          "@vaadin/rich-text-editor",
          "@vaadin/vaadin-lumo-styles/icons.js",
          "@vaadin/component-base",
          "@vaadin/a11y-base",
          "@vaadin/field-base",
          "@vaadin/input-container",
          "@vaadin/vaadin-themable-mixin",
          "@vaadin/vaadin-development-mode-detector",
          "@vaadin/vaadin-usage-statistics",
          "@open-wc/dedupe-mixin",
          "highcharts",
          "ol",
          "rbush",
          "quickselect",
          "marked",
          "dompurify",
          "lit",
          "lit/async-directive.js",
          "lit/decorators.js",
          "lit/decorators/custom-element.js",
          "lit/decorators/event-options.js",
          "lit/decorators/property.js",
          "lit/decorators/query-all.js",
          "lit/decorators/query-assigned-elements.js",
          "lit/decorators/query-assigned-nodes.js",
          "lit/decorators/query-async.js",
          "lit/decorators/query.js",
          "lit/decorators/state.js",
          "lit/directive-helpers.js",
          "lit/directive.js",
          "lit/directives/async-append.js",
          "lit/directives/async-replace.js",
          "lit/directives/cache.js",
          "lit/directives/choose.js",
          "lit/directives/class-map.js",
          "lit/directives/guard.js",
          "lit/directives/if-defined.js",
          "lit/directives/join.js",
          "lit/directives/keyed.js",
          "lit/directives/live.js",
          "lit/directives/map.js",
          "lit/directives/range.js",
          "lit/directives/ref.js",
          "lit/directives/repeat.js",
          "lit/directives/style-map.js",
          "lit/directives/template-content.js",
          "lit/directives/unsafe-html.js",
          "lit/directives/unsafe-mathml.js",
          "lit/directives/unsafe-svg.js",
          "lit/directives/until.js",
          "lit/directives/when.js",
          "lit/html.js",
          "lit/polyfill-support.js",
          "lit/static-html.js",
        ];
        config.optimizeDeps!.exclude = [];
      },
    },
  ],
});

export default overrideVaadinConfig(customConfig);
